// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jdn-1no8TBBHxs2KUHfh8xvvjDTooyY',
    appId: '1:10903919130:web:9e8cbec1ba1866a5f68fa3',
    messagingSenderId: '10903919130',
    projectId: 'gotcha-d6acc',
    authDomain: 'gotcha-d6acc.firebaseapp.com',
    storageBucket: 'gotcha-d6acc.firebasestorage.app',
    measurementId: 'G-QYL0NFY9D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsBRUpTVJaU22_NcGyYK3TdCdnWEko_Uk',
    appId: '1:10903919130:android:773ce68c7c33006df68fa3',
    messagingSenderId: '10903919130',
    projectId: 'gotcha-d6acc',
    storageBucket: 'gotcha-d6acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOZLJVkZVtLiwtxlKYYvPmgVs30DHKW7E',
    appId: '1:10903919130:ios:95404908b6480c7df68fa3',
    messagingSenderId: '10903919130',
    projectId: 'gotcha-d6acc',
    storageBucket: 'gotcha-d6acc.firebasestorage.app',
    iosBundleId: 'com.example.gotchaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOZLJVkZVtLiwtxlKYYvPmgVs30DHKW7E',
    appId: '1:10903919130:ios:95404908b6480c7df68fa3',
    messagingSenderId: '10903919130',
    projectId: 'gotcha-d6acc',
    storageBucket: 'gotcha-d6acc.firebasestorage.app',
    iosBundleId: 'com.example.gotchaApp',
  );
}
